import Head from 'next/head';
import getData from '../utils/getData';
import Hero from '../components/landing/Hero';
import Subtitle from '../components/landing/Subtitle';
import Faqs from '../components/landing/Faqs';
import Sponsors from '../components/landing/Sponsors';

export default function Home({ faqs }) {
  return (
    <div>
      <Head>
        <title>2018 IDAS International Conference</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Hero />
        <Subtitle />
        <Faqs faqs={faqs} />
        <Sponsors />
      </main>
    </div>
  );
}

export async function getStaticProps() {
  const query = `{
    faqs {
      answer
      id
      question
    }
  }
  `;

  const { faqs } = await getData(query);

  return {
    props: {
      faqs,
    },
  };
}
